---
  - name: Installing postgres DB
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - postgresql-server
      - postgresql-contrib
      - python-psycopg2

  - name: Check if PostgreSQL database is initialized.
    stat:
      path: "{{ postgresql_data_dir }}/PG_VERSION"
    register: pgdata_dir_version

  - name: Ensure PostgreSQL database is initialized.
    command: postgresql-setup initdb
    when: not pgdata_dir_version.stat.exists

  - name: Adding firewalld rule for postgres
    firewalld:
      port: 5432/tcp
      permanent: yes
      state: enabled

  - name: Starting and enabling postgresql service
    service:
      name: postgresql
      state: started
      enabled: yes

