  - name: Red Hat Enterprise Linux 7.5 golddisk
    yum_repository:
      name: RHEL75-golddisk
      description: RHEL7.5 golddisk
      file: rhel7media
      baseurl: http://{{ http_yum_server }}/RHEL7GOLD/
      gpgcheck: no
      enabled: yes

  - name: Red Hat Enterprise Linux 7.5 vanila
    yum_repository:
      name: RHEL75-vanila
      description: RHEL7.5 vanila
      file: rhel7media
      baseurl: http://{{ http_yum_server }}/RHEL7Vanila/
      gpgcheck: no
      enabled: yes